<a href="https://colab.research.google.com/github/mn-ethel/Numpy-pratice/blob/main/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Arrays

1 dimensional array

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a)
a.shape #Outputs four which means they are four columns and it is 1 dimensional

[1 2 3 4]


(4,)

2 dimensional array

In [4]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape #output(2,4) shows 2 dimensional array

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

Specifying a data type

In [6]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in arrays

In [7]:
x=np.zeros((4,5)) #Numpy array of zeros
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
y=np.ones((4,3)) #Numpy array of ones
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Array of a particular value

In [9]:
m=np.full((4,5),6)
print(m)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


Identity Matrix

In [10]:
r=np.eye(6)
print(r)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Random Values array

In [12]:
j=np.random.random((2,5))
print(j) # Values are between one and zero

[[0.90483313 0.79345125 0.2460524  0.39603832 0.56062114]
 [0.09386543 0.45009731 0.18876302 0.29874944 0.47205512]]


Random integer values array within specified range

In [13]:
f=np.random.randint(10,100,(6,7))
print(f)

[[14 26 23 11 42 97 43]
 [57 39 48 76 42 76 40]
 [17 75 86 52 22 20 59]
 [87 14 73 65 56 31 38]
 [59 82 39 20 34 10 67]
 [33 68 88 83 88 41 91]]


In [18]:
g = np.arange(10,30,5) # In steps of 5
print(g)

[10 15 20 25]


Converting a list to a numpy array

In [21]:
list1=[2,3,4,5,6]
np_array=np.asarray(list1)
print(np_array)
type(np_array)

[2 3 4 5 6]


numpy.ndarray